blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/Elephant-Augments/modpack-template/discussions
    about: Please direct any questions or general feedback to the discussions tab.
