name: Nitpick
description: Polish tweaks and other inconveniences that are too small to be labeled bugs.
title: "[Nitpick] "
labels: [":space_invader: nitpick"]
type: polish
body:

  - type: dropdown
    id: mod
    attributes:
      label: Modpack/Mod
      options:
        - Project Chobani Modpack
        - Create Fuel Tank
        - Fish Patty
        - Nifty Ships
        - Party Up!
        - Project Artisan
        - Project Evergreen
        - Project Odyssey
        - Sophisticated Memory
        - Temporal Timelines
        - Villager Quests
        - Waystop
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: A short description of the problem.
    validations:
      required: true
