name: Nitpick
description: Polish tweaks and other inconveniences that are too small to be labeled bugs.
title: "[Nitpick] "
labels: [":space_invader: nitpick"]
type: polish
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: A short description of the problem.
    validations:
      required: true
