name: Suggestion
description: Suggest a new feature or other mod alteration.
title: "[Suggestion] "
labels: [":sparkles:  enhancement"]
type: feature
body:
  - type: dropdown
    id: mod
    attributes:
      label: Modpack/Mod
      options:
        - Project Chobani Modpack
        - Create Fuel Tank
        - Fish Patty
        - Nifty Ships
        - Party Up!
        - Project Artisan
        - Project Evergreen
        - Project Odyssey
        - Sophisticated Memory
        - Temporal Timelines
        - Villager Quests
        - Waystop
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Describe the new feature or alteration in detail.
    validations:
      required: true

  - type: textarea
    id: related_context
    attributes:
      label: Related Context
      placeholder: Any related mods or references we should know about?
    validations:
      required: false
